CREATE TABLE TIME ( NOME VARCHAR2(20) NOT NULL, ESTADO CHAR(2),
   TIPO VARCHAR2(12),
   SALDO_GOLS NUMBER(4),
   CONSTRAINT PK_TIME PRIMARY KEY(NOME),
   CONSTRAINT CK_TIPO CHECK(UPPER(TIPO) IN ('AMADOR', 'PROFISSIONAL'))
);

CREATE TABLE USUARIO ();
CREATE TABLE USUARIO_IDIOMA ();
CREATE TABLE GUIA ();
CREATE TABLE TURISTA ();
CREATE TABLE TURISTA_GOSTA ();
CREATE TABLE PASSEIO ();
CREATE TABLE FOTOS_PASSEIO ();
CREATE TABLE PASSEIO_ATRACAO ();

CREATE TABLE ATRACAO ();
CREATE TABLE FOTOS_ATRACAO ();
CREATE TABLE ATRACAO_CATEGORIA ();
CREATE TABLE CATEGORIA ();

CREATE TABLE MENSAGEM ();

CREATE TABLE ATENDENTE ();
CREATE TABLE TECNICO ();


